Repository IT-Cotato/11th-TimeTile-FE, pull requests merged in 2025-07, with the labels that each got.

#5 [chore] storybook 확인 및 CI/CD 설정
  .github/workflows/chromatic.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/assets/icons/Frown.tsx
  src/components/atoms/Buttons/Buttons.stories.ts
  src/components/atoms/Buttons/index.tsx
  src/components/atoms/Text/Text.stories.ts
  src/components/atoms/Text/index.tsx
  src/components/layouts/FlexBox.tsx
  src/constants/atoms/button.ts
  src/model/components/Button.ts
  src/model/components/Text.ts
  src/styles/emotion.d.ts
  src/styles/palette.ts
  src/styles/theme.ts
  src/styles/typo.ts
  vitest.config.ts
  vitest.shims.d.ts
Labels: chore

#19 [fix] storybook 설정 변경
  .github/workflows/chromatic.yml
Labels: fix

#20 [fix] setting 변경
  .github/workflows/chromatic.yml
Labels: fix

#22 [UI] 아티스트 타임라인 프로필 UI 구현
  package.json
  pnpm-lock.yaml
  src/assets/icons/MoveLeftIcon.tsx
  src/assets/icons/MoveRightIcon.tsx
  src/components/Timeline/TileCard/TileCard.stories.ts
  src/components/Timeline/TileCard/index.tsx
  src/components/atoms/ArtistProfileCard/ArtistProfileCard.stories.ts
  src/components/atoms/ArtistProfileCard/index.tsx
  src/components/atoms/TimeLineTooltip/TimeLineTooltip.stories.ts
  src/components/atoms/TimeLineTooltip/index.tsx
  src/components/atoms/Tooltip/Tooltip.stories.ts
  src/components/atoms/Tooltip/index.tsx
  src/styles/tooltip.ts
Labels: feat

#25 [UI] 온보딩 input ,button 컴포넌트
  src/app/onboarding/page.tsx
  src/assets/icons/CheckIcon.tsx
  src/assets/icons/EyeFalseIcon.tsx
  src/assets/icons/EyeVisibleIcon.tsx
  src/assets/images/SymbolLogo.tsx
  src/assets/images/SymbolTextLogo.tsx
  src/assets/images/TextLogo.tsx
  src/components/atoms/CheckButton/CheckButton.stories.ts
  src/components/atoms/CheckButton/index.tsx
  src/components/atoms/OnboardingInput/OnboardingInput.stories.ts
  src/components/atoms/OnboardingInput/index.tsx
  src/components/atoms/Tooltip/index.tsx
  src/styles/typo.ts
Labels: ui
